### PR TITLE
Project Setup

### PR DESCRIPTION
**Pull request by aepelde**
This PR includes all project setup and is the placeholder to apply the infrastructure

### CODE REVIEW

**Review by juanfi — APPROVED** [review]
LGTM 👍

**Comment by aepelde** [comment]
atlantis plan -p repository

**Comment by aepelde** [comment]
atlantis apply -p repository

**Comment by aepelde** [comment]
atlantis plan -p prod

**Comment by aepelde** [comment]
atlantis apply -p prod

**Pull request merged**
