### PR TITLE
Create RDS PostgreSQL resource

### PR DESCRIPTION
**Pull request by aepelde**
# Short Description

Create an RDS PostgreSQL resource for the application.

## Types of changes

- ✨  New feature (non-breaking change which adds functionality)

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by aepelde** [comment]
atlantis plan -p prod

**Review by juanfi — APPROVED** [review]
LGTM

**Comment by aepelde** [comment]
atlantis apply -p prod

**Comment by aepelde** [comment]
atlantis plan -p prod

**Pull request merged**
